from django.urls import path
from . import admin_views

urlpatterns = [
    path('stats/', admin_views.admin_stats, name='admin_stats'),
    path('businesses/', admin_views.admin_businesses, name='admin_businesses'),
    path('businesses/create/', admin_views.admin_create_business, name='admin_create_business'),
    path('businesses/bulk-import/', admin_views.admin_bulk_import_businesses, name='admin_bulk_import_businesses'),
    path('businesses/bulk-import/template/', admin_views.admin_business_import_template, name='admin_business_import_template'),
    path('businesses/<int:pk>/', admin_views.admin_update_business, name='admin_update_business'),
    path('businesses/<int:pk>/detail/', admin_views.admin_business_detail, name='admin_business_detail'),
    path('businesses/<int:pk>/delete/', admin_views.admin_delete_business, name='admin_delete_business'),
    path('businesses/<int:pk>/archive/', admin_views.admin_archive_business, name='admin_archive_business'),
    path('businesses/<int:pk>/restore/', admin_views.admin_restore_business, name='admin_restore_business'),
    path('businesses/qr/bulk/', admin_views.admin_business_qr_bulk, name='admin_business_qr_bulk'),
    path('businesses/export/', admin_views.admin_business_export, name='admin_business_export'),
    path('businesses/<int:pk>/qr/', admin_views.admin_business_qr, name='admin_business_qr'),
    path('users/', admin_views.admin_users, name='admin_users'),
    path('users/<int:pk>/', admin_views.admin_update_user, name='admin_update_user'),
    path('users/<int:pk>/delete/', admin_views.admin_delete_user, name='admin_delete_user'),
    path('users/<int:pk>/reset-password/', admin_views.admin_reset_user_password, name='admin_reset_user_password'),
    path('orders/', admin_views.admin_orders, name='admin_orders'),
    path('reviews/', admin_views.admin_reviews, name='admin_reviews'),
    path('reviews/<int:pk>/', admin_views.admin_update_review, name='admin_update_review'),
    path('reviews/<int:pk>/delete/', admin_views.admin_delete_review, name='admin_delete_review'),
    path('categories/', admin_views.admin_categories, name='admin_categories'),
    path('categories/create/', admin_views.admin_create_category, name='admin_create_category'),
    path('categories/<int:pk>/delete/', admin_views.admin_delete_category, name='admin_delete_category'),
    path('advertisements/', admin_views.admin_advertisements, name='admin_advertisements'),
    path('advertisements/create/', admin_views.admin_create_advertisement, name='admin_create_advertisement'),
    path('advertisements/<int:pk>/', admin_views.admin_update_advertisement, name='admin_update_advertisement'),
    path('advertisements/<int:pk>/delete/', admin_views.admin_delete_advertisement, name='admin_delete_advertisement'),
]