# Generated by Django 6.0.7 on 2026-08-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_accepts_orders_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='card_payment',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'Not Applicable')], default='na', max_length=3),
        ),
        migrations.AddField(
            model_name='business',
            name='free_wifi',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'Not Applicable')], default='na', max_length=3),
        ),
        migrations.AddField(
            model_name='business',
            name='has_parking',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_registered',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='offer_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='offer_package',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'Not Applicable')], default='na', max_length=3),
        ),
        migrations.AddField(
            model_name='business',
            name='payment_mode',
            field=models.CharField(choices=[('cash_only', 'Cash Only'), ('online', 'Online Payment')], default='cash_only', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='smoking',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'Not Applicable')], default='na', max_length=3),
        ),
        migrations.AlterField(
            model_name='business',
            name='accepts_orders',
            field=models.BooleanField(default=False),
        ),
    ]
