# Generated by Django 6.0.7 on 2026-08-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_relax_required_fields_and_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/'),
        ),
    ]
