# Generated by Django 6.0.7 on 2026-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_add_more_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'code_sequences',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='branch_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='category_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
